### ISSUE TITLE
unable to download files from Baidu cloud

### ISSUE THREAD

**Issue by meokey** [Martion-z/Paddle-PULSE#1]
unable to download files such as pretrain GAN model from Baidu cloud.
Could you kindly upload it to somewhere else with public access w/o client? Thanks.

**Comment by Martion-z** [comment]
you can also go to my AI Studio Project(https://aistudio.baidu.com/aistudio/projectdetail/2255411), and the pretrain GAN model is placed in models/cache directory

**Comment by Martion-z** [comment]
you can also go to my AI Studio Project(https://aistudio.baidu.com/aistudio/projectdetail/2255411), and the pretrain GAN model is placed in models/cache directory

**Comment by meokey** [comment]
thanks I got it
